### ISSUE TITLE
Author Contributions

### ISSUE THREAD

**Issue by mprib** [cvjena/JeFaPaTo#2]
As part of the JOSS review process I'm opening an issue here and will link to it from the Review Checklist. If I'm misunderstanding the workflow, someone please let me know as this is my first JOSS review.

Based on the contribution summary [here](https://github.com/cvjena/JeFaPaTo/graphs/contributors) I'm only seeing direct code contributions from @Timozen. Would it be possible to describe the contributions of the other listed authors?

Thank you!

Mac

**Comment by Timozen** [comment]
Here are some of the contributions the other authors made.

Oliver Mothes did the original concept of the tool and the first implementations of the software. However, these comments are somehow not visible on GitHub. I've attached parts of the commit history of our internal server (which hosts a local copy of this repo). There, he is part of the commit history and contributor to the code.

Joachim Denzler supported the tool not in a coding manner but gave recommendations for algorithms, computer vision concepts, and general experimental setups for the experiments. Hence, he only indirectly contributed to the tool that needed to be visible in the commit history.

Orlando Guntinas-Lichius is the medical expert for the software, and it is his actual brainchild. He gave feedback on the usability of the tool, assessed the relevant medical extracted features, and is the test subject in the videos shown in the examples in this repository. Therefore, he could not contribute to the code of the software itself.

![image](https://github.com/cvjena/JeFaPaTo/assets/13612390/de29d12f-417b-41df-a48f-79239e1b8a92)

**Comment by draabe** [comment]
Hi @mprib , @Timozen ,

I've came across the same question, but with @Timozen 's explanation I'm confident that the JOSS criteria for authorship are met.

**Comment by mprib** [comment]
Sounds good to me. I'm happy to check this item off and will close the issue.
