### ISSUE TITLE
Trouble running on Ubuntu 22.04

### ISSUE THREAD

**Issue by mprib** [cvjena/JeFaPaTo#3]
Hello @Timozen!

I'm going to use this issue as a running thread of any questions / issues / observations that come up while I confirm the functionality of JeFaPaTo. Apologies in advance for the stream-of-consciousness while I work through this....

# Launch
I have successfully launched the compiled binary on Ubuntu 22.04

Please note that in https://github.com/cvjena/JeFaPaTo/blob/main/INSTALL.md the link to the README.md is dead. 

I'm a casual linux user (otherwise on windows 10) and needed to refresh my memory about `chmod +x JeFaPaTo_linux` and then `./JeFaPaTo_linux` to launch. This may be helpful to include somewhere.

# Data Upload

I have uploaded an mp4 of myself via the GUI
- side note: is mp4 required? I could drag a .mov into the box, but the upload interface seemed to only allow .mp4

# Analyze Facial Features

Instructions from the README:
```
Facial Features

    Start JeFaPaTo
    Select the video file or drag and drop it into the indicated area
    The face should be found automatically; if not, adjust the bounding box
    Select the facial features you want to analyze in the sidebar
    Press the play button to start the analysis
```

I do not see a "play" button, but there is an "Analyze" button. When I click this nothing happens and that seems to be as far as I can get.

![image](https://github.com/cvjena/JeFaPaTo/assets/31831778/25fda32e-0351-4436-be88-6d964696d53e)

Could you provide any guidance at this stage to move forward?

Thank you!

Mac

**Comment by Timozen** [comment]
Hey Mac,

Thank you for reviewing our tool!

Unfortunately I am currently out of country and can only access GitHub via my phone 😅

Therefore I will come back to support you as soon as possible once I have a stable internet connection ^^

Best 
Tim

**Comment by mprib** [comment]
Hi Tim,

I ended up just cloning the repo and running `main.py`. I'm able to successfully analyze a video to get EAR scores, however I'm having trouble with the next phase of the processing. I will create a new issue to describe what I'm seeing. I'll leave this one up here still as it seemed like I was having issues on the Ubuntu install, but feel free to close. If I can verify the functionality with an editable install, that works for me.

Mac

**Comment by Timozen** [comment]
Thank you already for your insights! I am now back in the office and will take a look at all the issues asap.

Tim
