### ISSUE TITLE
Blink Extraction Hangs

### ISSUE THREAD

**Issue by mprib** [cvjena/JeFaPaTo#4]
Hello,

I have done an editable install on Windows 10. 

I was able to get the EAR scores output to a `csv` file in the facial extraction tab. Moving to the Blinking Extaction tab I was able to import the EAR scores, but then clicking `Extract Blinks` resulted in the processing freezing at 40%. I tried a few times and it consistently froze at 40%.

I'm not sure if I'm failing to configure the settings in the appropriate way or if the data I'm providing is sufficient (about 10 seconds of me blinking on camera). Any guidance is appreciated.

Thanks!

Mac

![image](https://github.com/cvjena/JeFaPaTo/assets/31831778/40905285-1702-4923-8722-dbc10a4fd6f4)

**Comment by Timozen** [comment]
Hi @mprib,

I investigated the issues and pushed some fixes into the `development` branch of the tool. If you could switch to the branch, checkout the latest commit, and rerun the extraction, it should work now (or at least give a more helpful error message ^^)

Additionally, I updated the interface to include a button to inform the user about recommended settings for 30FPS and 240FPS.
Furthermore, each setting now has its help button to access a more detailed description and the recommended setting again (access by clicking or hovering).

Lastly, I added a 30 FPS EAR score file in the [examples](https://github.com/cvjena/JeFaPaTo/tree/main/examples) repo folder.
More video files for testing are available in the [tests](https://github.com/cvjena/JeFaPaTo/tree/main/tests/files) folder for automatic testing.

In the attached screenshot, you can see the interface changes.

![GUI help changes](https://github.com/cvjena/JeFaPaTo/assets/13612390/78704c2f-c9af-4f25-a66d-602b4a00cee7)

**Comment by Timozen** [comment]
If there is any issue please let new know :) You can also send your EAR score file, and I can investigate further issues.

**Comment by mprib** [comment]
Happy to report that I was able to process some video I recorded myself and get successful output on the development branch. The specific domain knowledge is well outside my wheelhouse, but I'm willing to  believe the results given my attempts at asymmetrical and partial blinking:
![image](https://github.com/cvjena/JeFaPaTo/assets/31831778/00cd4b91-8814-4a88-9688-1d02ef1c9361)
