### ISSUE TITLE
Manuscript notes

### ISSUE THREAD

**Issue by mprib** [cvjena/JeFaPaTo#5]
Greetings. I have a handful of comments that may help improve the readability of the manuscript and one higher level comment regarding one of the specific checkboxes that JOSS provides in its checklist.

# Readability Comments

Line 41: "JeFaPoTo" -> JeFaPaTo
Lines 51- 52: sentence in need of revision "This summary enables a quick individualized analysis for each video, thus also patients, and can be included in medical reports."
Line 68: Consider revising use of "whereas" or restructuring sentence.
Line 84; should it be "or for further processing *by* JeFaPaTo"?
Line 104: "corresponding" may be a more appropriate word choice than "according" 
Line 107: "according" feels misused here... is it  "a single blink to visualize the corresponding period", not the  "according blink to visualize the according period"?
Line 111: "according" again feels like the wrong word. "Corresponding" may be better
129: "expert medical feedback"?
Lines 157-158: " Careful setting up the experiment can reduce"... consider revising... something like "Care must be taken when recording video to reduce..."

# State of the field

It is not clear to me if there are alternative tools that someone might use to perform this kind of analysis. There is the statement that "To analyze the blinking behavior in detail, medical experts often use high-speed cameras to record the blinking process." This leaves me wondering how someone might process that data and it's not clear what would be used prior to JeFaPaTo. Perhaps briefly stating the methods used in the referenced EAR paper as a point of comparison. Even if it's just custom coding solutions for anyone interested in studying this, it would help to make that explicit.

**Comment by Timozen** [comment]
Thank you! I will change the paper accordingly. I will also add the recommended settings as discussed in #4

**Comment by Timozen** [comment]
Thank you very much for your feedback. We updated the paper accordingly and included also statement of the field inside the statement of need.

We Pushed the changes to the main branch and the paper should be downloadable via JOSS. 

If something is unclear or should be changed, please let us know  :)

**Comment by mprib** [comment]
LGTM!
